### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jianzhangbjz** [Hui-Zhi/kubernetes#1]
Hi Hui-Zhi,

**I clone the code, and exec "./hack/build-go.sh", but it came error(like below), can you help check it, or tell me how to use this code? Thanks in advance** 
"!!! Error in /home/zhangjian/kubernetes-try_nvidia_docker_merge_devices_support/hack/lib/golang.sh:395
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 1
Call stack:
  1: /home/zhangjian/kubernetes-try_nvidia_docker_merge_devices_support/hack/lib/golang.sh:395 kube::golang::build_binaries_for_platform(...)
  2: /home/zhangjian/kubernetes-try_nvidia_docker_merge_devices_support/hack/lib/golang.sh:536 kube::golang::build_binaries(...)
  3: hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /home/zhangjian/kubernetes-try_nvidia_docker_merge_devices_support/hack/lib/golang.sh:457
  '( kube::golang::setup_env; local host_platform; host_platform=$(kube::golang::host_platform); local goflags goldflags; eval "goflags=(${KUBE_GOFLAGS:-})"; goldflags="${KUBE_GOLDFLAGS:-} $(kube::version::ldflags)"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local parallel=false; if [[ ${#platforms[@]} -gt 1 ]]; then
    local gigs; gigs=$(kube::golang::get_physmem); if [[ ${gigs} -ge ${KUBE_PARALLEL_BUILD_MEMORY} ]]; then
        kube::log::status "Multiple platforms requested and available ${gigs}G >= threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in parallel"; parallel=true;
    else
        kube::log::status "Multiple platforms requested, but available ${gigs}G < threshold ${KUBE_PARALLEL_BUILD_MEMORY}G, building platforms in serial"; parallel=false;
    fi;
fi; if [[ "${parallel}" == "true" ]]; then
    kube::log::status "Building go targets for ${platforms[@]} in parallel (output will appear in a burst when complete):" "${targets[@]}"; local platform; for platform in "${platforms[@]}";
    do
        ( kube::golang::set_platform_envs "${platform}"; kube::log::status "${platform}: go build started"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-}; kube::log::status "${platform}: go build finished" ) &> "/tmp//${platform//\//_}.build" &
    done; local fails=0; for job in $(jobs -p);
    do
        wait ${job} || let "fails+=1";
    done; for platform in "${platforms[@]}";
    do
        cat "/tmp//${platform//\//_}.build";
    done; exit ${fails};
else
    for platform in "${platforms[@]}";
    do
        kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; kube::golang::set_platform_envs "${platform}"; kube::golang::build_binaries_for_platform ${platform} ${use_go_build:-};
    done;
fi )' exited with status 1
Call stack:
  1: /home/zhangjian/kubernetes-try_nvidia_docker_merge_devices_support/hack/lib/golang.sh:457 kube::golang::build_binaries(...)
  2: hack/build-go.sh:26 main(...)
Exiting with status 1"

**Comment by Hui-Zhi** [comment]
Please use the make command in the Kubernetes directory.

**Comment by jianzhangbjz** [comment]
Sorry for the late reply, use the "make release" or "make" command, it still errors.
The error info was the same as above, are there others needs attention?
go version is "go1.6.2 linux/amd64", docker version is "version 1.11.1, build 5604cbe"

**Comment by Hui-Zhi** [comment]
If it doesn't work for you, give a try to kubernetes/master branch frist.

**Comment by jianzhangbjz** [comment]
Thanks sincerely, it works now! 
BTW, how can I use this binary files under _output folder?
Can you share the Pod/RC/Service YAML files to use the GPUs? or kubectl command? or docs?

**Comment by Hui-Zhi** [comment]
Please the images you're going to use are based on cuda:7.5, and the yaml file could be looked like as below;
````yaml
apiVersion: v1
kind: Pod
metadata:
  name: xxx
spec:
  containers:
  - name: xxx
    image: xxx
    resources:
      requests:
        nvidiaGPU: 2

````

**Comment by jianzhangbjz** [comment]
Thanks a lot! but exec "./_output/local/bin/linux/amd64/**kubectl describe node**", I can get the GPU info, is it normal?

**Comment by Hui-Zhi** [comment]
Yes, but it could schedule GPU resource.

**Comment by jianzhangbjz** [comment]
Okay, why not add this feature? It would be convenient for managing nodes.

**Comment by jianzhangbjz** [comment]
Okay, why not add this feature? It would be convenient for managing nodes.

**Comment by Hui-Zhi** [comment]
Will be added in the future.

**Comment by jianzhangbjz** [comment]
OK, thanks!
